restroomsaround/apps/location/urls.py
from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt

from .views import LocationView, SaveLocation

urlpatterns = [

	url(r'^nearby/', LocationView.as_view(), name='nearby_locations'),
	url(r'^save/', csrf_exempt(SaveLocation.as_view()), name='save_location'),

]

restroomsaround/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from apps.location.views import HomePageView

urlpatterns = [

    url(r'^$', HomePageView.as_view(), name='home_page'),

    url(r'^location/',
        include('apps.location.urls', namespace="location")),

    url(r'^admin/', include(admin.site.urls)),
]

restroomsaround/apps/location/models.py
from django.contrib.gis.db import models

class TimeAuditModel(models.Model):

	created_at = models.DateTimeField(u'Created At', auto_now_add=True, null=True)
	updated_at = models.DateTimeField(u'Last Updated At', auto_now=True, null=True)

	class Meta:
		abstract = True


class LocationModel(TimeAuditModel):

	address = models.CharField(max_length=255, verbose_name="Location of the rest room", null=True, blank=True)
	lat = models.FloatField(u'Latitude', blank=True)
	lng = models.FloatField(u'Longitude', blank=True)
	location = models.PointField(blank=True, null=True, verbose_name='Longitude/Latitude', geography=True)
	objects = models.GeoManager()

	def __unicode__(self):
		return unicode(self.id)

	class Meta:
		db_table = 'restroom'
		verbose_name_plural = 'Rest Rooms Location'

restroomsaround/apps/location/forms.py
from django.forms import ModelForm, TextInput
from apps.location.models import LocationModel

class LocationForm(ModelForm):

	class Meta:
		model = LocationModel
		fields = ['address', 'lat', 'lng']
		widgets = {
			'address': TextInput(attrs={'class': 'form-control', 'placeholder': 'Current address'}),
			'lat': TextInput(attrs={'class': 'form-control', 'placeholder': 'Latitude'}),
			'lng': TextInput(attrs={'class': 'form-control', 'placeholder': 'Longitude'})
		}

restroomsaround/apps/location/views.py
from django.shortcuts import render
from django.views import generic
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.contrib.gis import geos, measure

from apps.location.models import LocationModel
from apps.location.forms import LocationForm

class HomePageView(generic.ListView):

	template_name = 'location/index.html'

	def get(self, request, *args, **kwargs):
		formObj = LocationForm(request.GET)
		return render(request, self.template_name, {
				'form': formObj,
			})


class LocationView(generic.ListView):

	template_name = 'location/nearby.html'

	def get(self, request, *args, **kwargs):
		formObj = LocationForm(request.GET)
		near_by_point = None
		if formObj.is_valid():
			lat = formObj.cleaned_data['lat']
			lng = formObj.cleaned_data['lng']
			default_distance = 10
			distance_from_point = {'km':default_distance}
			if lat and lng:
				current_point=geos.fromstr("POINT(%s %s)" % (lng, lat))
				near_by_point = LocationModel.objects.filter(
					location__distance_lte=(
						current_point,measure.D(**distance_from_point)))
				near_by_point = near_by_point.distance(current_point).order_by(
					'distance')

		html = render_to_string(self.template_name, {'restrooms': near_by_point})
		return JsonResponse({
				'points': html
			})


class SaveLocation(generic.CreateView):

	def post(self, request, *args, **kwargs):
		formObj = LocationForm(request.POST)
		info_msg, bstrp_cls = [None]*2
		d = {}
		if formObj.is_valid():
			lat = formObj.cleaned_data.get('lat', None)
			lng = formObj.cleaned_data.get('lng', None)
			if lat and lng:
				point = "POINT({} {})".format(lng, lat)
				point = geos.fromstr(point)
				pointExist = LocationModel.objects.filter(location__distance_lte=(point,measure.D(mi=0.001))).distance(point)
				if not pointExist:
					new_point = formObj.save(commit=False)
					new_point.location = point
					new_point.save()
					info_msg = "Your location is successfully saved"
					bstrp_cls = 'alert-success'
				else:
					info_msg = 'This location already exists in our database.'
					bstrp_cls = 'alert-warning'
		d['msg'] = info_msg
		d['cls'] = bstrp_cls
		return JsonResponse(d)

restroomsaround/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
	<meta name="author" content="">

	<title>
		{% block title %}Rest Rooms Around{% endblock %}
	</title>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

	{% block custom_css %}
	{% endblock %}

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

	{% block custom_javascript %}
	{% endblock %}

</head>
<body>

	<nav class="navbar navbar-inverse">
		<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#">Restroom</a>
			</div>

			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
				</ul>
			</div><!-- /.navbar-collapse -->
		</div><!-- /.container-fluid -->
	</nav>

	<div class="container-fluid">
		{% block container %}
		{% endblock %}
	</div>

</body>
</html>

restroomsaround/templates/location/index.html
{% extends "base.html" %}

{% block custom_css %}
	<style>
		#map {
		width: auto;
		height: 400px;
		}

		ul{
			list-style-type:none;
		}
	</style>
{% endblock %}

{% block custom_javascript %}

	<script src="https://maps.googleapis.com/maps/api/js"></script>

	<script>

		var marker, map;

		var circle ={
			path: google.maps.SymbolPath.CIRCLE,
			fillColor: 'green',
			fillOpacity: .9,
			scale: 4.5,
			strokeColor: 'green',
			strokeWeight: 1
		};

	 	function initialize(){

			var mapCanvas = document.getElementById('map');
			var mapOptions = {
				center: new google.maps.LatLng(44.5403, -78.5463),
				zoom: 12,
				mapTypeId: google.maps.MapTypeId.ROADMAP
			}
			map = new google.maps.Map(mapCanvas, mapOptions);
			console.log(map);
			getCurrentLocation();

	 	}

	 	function getCurrentLocation(){

	 		if(navigator.geolocation){
	 			navigator.geolocation.getCurrentPosition(function(position){
	 				var pos = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
	 				marker = new google.maps.Marker({
	 					position: pos,
	 					draggable: true,
	 					animation: google.maps.Animation.DROP,
	 					map: map
	 				});
	 				map.setCenter(pos);
	 				updatePositionAsMarkerMoves();

	 				google.maps.event.addListener(marker, 'click', function(event){
	 						updatePositionAsMarkerMoves();
	 				});

	 				google.maps.event.addListener(marker, 'dragend', function(event){
	 						updatePositionAsMarkerMoves();
	 				});
	 			});
	 		} else {
	 			console.log('HTML 5 not supported');
	 		}

	 	}

	 	function getMarkerPosition(){
	 		var currentPos = marker.getPosition();
	 		return [currentPos.lat(), currentPos.lng()]
	 	}

	 	function updatePositionAsMarkerMoves(){

	 		var currentPos = getMarkerPosition();
	 		var currentLat = currentPos[0];
	 		var currentLng = currentPos[1];

	 		var latLng = new google.maps.LatLng(currentLat, currentLng);
	 		var geocoder = new google.maps.Geocoder();

	 		geocoder.geocode({'latLng':latLng}, function(results, status){
	 			if(status == google.maps.GeocoderStatus.OK){
	 				if(results[0]){
	 					var address = results[0].formatted_address;
	 					$('#id_address').val(address);
	 				}
	 			}
	 		});

	 		fetchNearByLocs(currentLat, currentLng);
	 	}

	 	function setPosition(currentLat, currentLng){

	 		$('#id_lat').val(currentLat);
			$('#id_lng').val(currentLng);

	 	}

	 	function saveLocation(){

	 		$('#saveButton').html('<i class="fa fa-spinner fa-spin"></i>&nbsp;Saving')
	 		var currentPos = getMarkerPosition();
	 		var currentLat = currentPos[0];
	 		var currentLng = currentPos[1];

			setPosition(currentLat, currentLng);

	 		$.ajax({
	 			url: 'location/save/',
	 			type: 'post',
	 			data: $('#locationForm').serialize(),
	 			success: function(data){
	 				console.log('success');
	 				$('#saveButton').html('Save&nbsp;<i class="fa fa-floppy-o">');
	 				$('#alertDiv').addClass(data.cls);
	 				$('#alertDiv').show();
	 				$('#helpMsg').text(data.msg);
	 				fetchNearByLocs(currentLat, currentLng);
	 			},
	 			error: function(err, textStatus, errThrown){
	 				console.log('error in saving location');
	 			}
	 		});
	 	}

	 	function fetchNearByLocs(currentLat, currentLng){

			$('#progressBar').show();

			setPosition(currentLat, currentLng);

	 		$.ajax({
	 			url: 'location/nearby/',
	 			type: 'get',
	 			data: $('#locationForm').serialize(),
	 			success: function(data){
	 				console.log('success');
	 				$('#progressBar').hide();
	 				$('#placesDiv').empty();
	 				$('#placesDiv').html(data.points);
	 				var markerData = $.parseHTML(data.points)[1];
	 				$(markerData).find('li').each(function(i,c){

	 					var latitude = $(c).find('.latitude').text();
	 					var longitude = $(c).find('.longitude').text();
	 					var name = $(c).text();
	 					new google.maps.Marker({
							position: new google.maps.LatLng(latitude, longitude),
							map: map,
							icon: circle,
							title: name,
						});
					});
				},
				error: function(err, textStatus, errThrown){
					console.log('error');
				}
			});
		}

	 	google.maps.event.addDomListener(window, 'load', initialize);
	</script>

{% endblock %}

{% block container %}

	<div class="row">
		<div class="col-sm-6 col-sm-offset-1">
			<div class="alert alert-dismissible" role="alert" id="alertDiv" style="display:none;">
				<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<p class="text-left" id="helpMsg"></p>
			</div>
		</div>
		<div class="col-sm-5">
			<div class="progress" id="progressBar" style="display:none;">
				<div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;" >
				</div>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-sm-6 col-sm-offset-1">
			<div id="map">
			</div>
		</div>
		<div class="col-sm-5">
			<h3>Nearby Places</h3>
			<div id="placesDiv"></div>
		</div>
	</div>

	<div class="row" style="padding-top:10px;">
		<form id="locationForm">
			<div class="col-sm-5 col-sm-offset-1">
				{{form.address}}
			</div>
	</div>

	<div class="row" style="padding-top:10px;">
		<div class="col-sm-2 col-sm-offset-1">
			{{form.lat}}
		</div>
		<div class="col-sm-2">
			{{form.lng}}
		</div>
		<div class="col-sm-1">
			<button type="button" class="btn btn-success" onclick="saveLocation();" id="saveButton">
				Save&nbsp;<i class="fa fa-floppy-o"></i>
			</button>
		</div>
		</form>
	</div>

{% endblock %}

restroomsaround/templates/location/nearby.html
{% if restrooms %}
	<ul class="icons-ul">
		{% for i in restrooms %}
			<li>
				<address>{{i.address}}</address>
				<span class="latitude hidden">{{i.lat}}</span>
				<span class="longitude hidden">{{i.lng}}</span>
			</li>
		{% endfor %}
	</ul>
{% else %}
	<div class="alert alert-dismissible alert-info" role="alert" >
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<p class="text-left">Oops! We could not find any rest room near to you within 10 km range.</p>
	</div>
{% endif %}